/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package proyectoagenciavehiculos;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 3st3b
 */
public class ventanaListaVehiculosVenta extends javax.swing.JDialog {

    /**
     * Creates new form ventanaListaVehiculosVenta
     */
    public ventanaListaVehiculosVenta(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTituloRegistro = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListaVehiculosVenta = new javax.swing.JTable();
        btnMostrarVehiculoVenta = new javax.swing.JButton();
        lblFondoListaVehiculos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloRegistro.setFont(new java.awt.Font("Dialog", 3, 30)); // NOI18N
        lblTituloRegistro.setForeground(new java.awt.Color(0, 0, 0));
        lblTituloRegistro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloRegistro.setText("Tabla con datos de los vehiculo a la venta.");
        getContentPane().add(lblTituloRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 650, 40));

        tblListaVehiculosVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblListaVehiculosVenta.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setViewportView(tblListaVehiculosVenta);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 650, 180));

        btnMostrarVehiculoVenta.setText("Mostrar Vehiculos Disponibles");
        btnMostrarVehiculoVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarVehiculoVentaActionPerformed(evt);
            }
        });
        getContentPane().add(btnMostrarVehiculoVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 190, 60));

        lblFondoListaVehiculos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Fondo Lista Vehiculos.jpg"))); // NOI18N
        getContentPane().add(lblFondoListaVehiculos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMostrarVehiculoVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarVehiculoVentaActionPerformed
        // TODO add your handling code here:
        //Seleccionar ruta del archivo para mostrarlo
        String rutaArchivoVehiculosV = "F:\\Progra 1\\Proyecto 2\\proyectoAgenciaVehiculos\\Lista Venta de Vehiculos.txt";
        File archivo = new File (rutaArchivoVehiculosV);

        //Try Catch
        try {
            BufferedReader buffer = new BufferedReader(new FileReader(archivo));
            
            DefaultTableModel modeloV = (DefaultTableModel) tblListaVehiculosVenta.getModel();
            
            modeloV.addColumn("Cedula");
            modeloV.addColumn("Placa");
            modeloV.addColumn("Marca");
            modeloV.addColumn("Modelo");
            modeloV.addColumn("Estilo");
            modeloV.addColumn("Cilindraje");
            modeloV.addColumn("Combustible");
            modeloV.addColumn("Transmision");
            modeloV.addColumn("Pasajeros");
            modeloV.addColumn("Color");
            
            Object[] lineasTablaV = buffer.lines().toArray();

            //
            for(int i = 0; i <lineasTablaV.length;i++){
                String linea = lineasTablaV[i].toString().trim();
                String [] datoFilaV = linea.split(";");
                //
                modeloV.addRow(datoFilaV);
            }

        } catch (Exception ex) {
            Logger.getLogger(ventanaListaVehiculosVenta.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_btnMostrarVehiculoVentaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaListaVehiculosVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaListaVehiculosVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaListaVehiculosVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaListaVehiculosVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ventanaListaVehiculosVenta dialog = new ventanaListaVehiculosVenta(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMostrarVehiculoVenta;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFondoListaVehiculos;
    private javax.swing.JLabel lblTituloRegistro;
    private javax.swing.JTable tblListaVehiculosVenta;
    // End of variables declaration//GEN-END:variables
}
