package proyectoagenciavehiculos;

import java.io.*;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.Scanner;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;

/**
 *
 * @author 3st3b
 */
public class ventanaCompraVehiculo extends javax.swing.JDialog {

    //Declarar Variables
    private TableRowSorter trsFiltro;
    String filtro;
    String mover;
    FileReader eliminarV;
    FileReader eliminarC;
    BufferedReader bufferV; 
    //Mostrar tabla
    String rutaArchivoVehiculosV = "F:\\Progra 1\\Proyecto 2\\proyectoAgenciaVehiculos\\Lista Venta de Vehiculos.txt";
    String rutaArchivoVehiculosC = "F:\\Progra 1\\Proyecto 2\\proyectoAgenciaVehiculos\\Lista Compra De Vehiculos.txt";
    DefaultTableModel modeloV;
    DefaultTableModel modeloC;

    //Instanciar los objetos para trabajar con otras clases y archivos
    compraVehiculo iCompraVehiculo = new compraVehiculo();
    archivoCompraVehiculos iArchivoCompraVehiculos = new archivoCompraVehiculos();

    /**
     * Creates new form ventanaCompraVehiculo
     */
    public ventanaCompraVehiculo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(parent);
        //Llamado metodo mostrar tabla venta
        mostrarTablaVenta();
        //Llamado metodo mostrar Tabla Compra
        mostrarTablaCompra();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTituloCompra = new javax.swing.JLabel();
        lblSubtituloVenta = new javax.swing.JLabel();
        lblSubtituloCompra = new javax.swing.JLabel();
        lblIndicacionCedula = new javax.swing.JLabel();
        lblIndicacionBusqueda = new javax.swing.JLabel();
        txtBusquedaVehiculo = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnGuardarCompra = new javax.swing.JButton();
        tblTablaVerVenta = new javax.swing.JScrollPane();
        tblListaVehiculosVenta = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTablaCompra = new javax.swing.JTable();
        txtCedulaCompra = new javax.swing.JTextField();
        lblFondoCompra = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloCompra.setFont(new java.awt.Font("Dialog", 3, 30)); // NOI18N
        lblTituloCompra.setForeground(new java.awt.Color(204, 204, 204));
        lblTituloCompra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloCompra.setText("Compra o Busqueda De Un Vehículo");
        getContentPane().add(lblTituloCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 530, 40));

        lblSubtituloVenta.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblSubtituloVenta.setForeground(new java.awt.Color(204, 204, 204));
        lblSubtituloVenta.setText("Lista Vehiculos Disponibles");
        getContentPane().add(lblSubtituloVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, -1, 20));

        lblSubtituloCompra.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblSubtituloCompra.setForeground(new java.awt.Color(204, 204, 204));
        lblSubtituloCompra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSubtituloCompra.setText("Lista Registro de Compra");
        getContentPane().add(lblSubtituloCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 220, 20));

        lblIndicacionCedula.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblIndicacionCedula.setText("Escriba su cédula para comprar");
        getContentPane().add(lblIndicacionCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, -1, 30));

        lblIndicacionBusqueda.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblIndicacionBusqueda.setText("Escoja el vehiculo que quiera por medio de la cédula ligada a el.");
        getContentPane().add(lblIndicacionBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, -1, 30));

        txtBusquedaVehiculo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBusquedaVehiculoKeyTyped(evt);
            }
        });
        getContentPane().add(txtBusquedaVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 320, -1));

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 160, 40));

        btnGuardarCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/payment-method (1).png"))); // NOI18N
        btnGuardarCompra.setText("Comprar Vehiculo");
        btnGuardarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarCompraActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardarCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, 160, 40));

        tblListaVehiculosVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblListaVehiculosVenta.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tblTablaVerVenta.setViewportView(tblListaVehiculosVenta);

        getContentPane().add(tblTablaVerVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 580, 100));

        tblTablaCompra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblTablaCompra.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tblTablaCompra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblTablaCompraKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblTablaCompra);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 580, 100));

        txtCedulaCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaCompraActionPerformed(evt);
            }
        });
        getContentPane().add(txtCedulaCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 210, -1));

        lblFondoCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Fondo Compra Vehiculo.jpg"))); // NOI18N
        lblFondoCompra.setText("jLabel1");
        getContentPane().add(lblFondoCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarCompraActionPerformed
      
        try {
            //Metodo guardar compra
            guardarCompra();
        } catch (IOException ex) {
            Logger.getLogger(ventanaCompraVehiculo.class.getName()).log(Level.SEVERE, null, ex);
        }

        //Codigo que permite mover los datos de las tablas
        DefaultTableModel modeloC = (DefaultTableModel) tblTablaCompra.getModel();
        DefaultTableModel modeloV = (DefaultTableModel) tblListaVehiculosVenta.getModel();

        Object[] fila = new Object[10];

        for (int j = 0; j < fila.length; j++) {
            fila[j] = tblListaVehiculosVenta.getValueAt(tblListaVehiculosVenta.getSelectedRow(), j);
        }
        modeloV.removeRow(tblListaVehiculosVenta.getSelectedRow());
        modeloC.addRow(fila);

        try {
             eliminarV = new FileReader("Lista Venta de Vehiculos.txt");
             eliminarC = new FileReader("Lista Compra De Vehiculos.txt");
             bufferV = new BufferedReader(eliminarV);
        } catch (Exception e) {

        }
        try {
            mover = bufferV.readLine();
           
        } catch (IOException ex) {
            Logger.getLogger(ventanaCompraVehiculo.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_btnGuardarCompraActionPerformed

    private void tblTablaCompraKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblTablaCompraKeyReleased
        // TODO add your handling code here:
        // buscador.setRowFilter(RowFilter.regexFilter(("(?i)"+tblTablaCompra)));
    }//GEN-LAST:event_tblTablaCompraKeyReleased

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

        txtBusquedaVehiculo.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(final KeyEvent e) {
                String cadena = txtBusquedaVehiculo.getText();
                txtBusquedaVehiculo.setText(cadena);
                repaint();
                filtro();
            }

        });

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtBusquedaVehiculoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaVehiculoKeyTyped
        // TODO add your handling code here:
        trsFiltro = new TableRowSorter(tblListaVehiculosVenta.getModel());
        tblListaVehiculosVenta.setRowSorter(trsFiltro);
    }//GEN-LAST:event_txtBusquedaVehiculoKeyTyped

    private void txtCedulaCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaCompraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaCompraVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaCompraVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaCompraVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaCompraVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ventanaCompraVehiculo dialog = new ventanaCompraVehiculo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    //Metodo Mostrar tabla Venta
    public void mostrarTablaVenta() {

        File archivo = new File(rutaArchivoVehiculosV);

        //Try Catch
        try {
            BufferedReader buffer = new BufferedReader(new FileReader(archivo));
            DefaultTableModel modeloV = (DefaultTableModel) tblListaVehiculosVenta.getModel();

            modeloV.addColumn("Cedula");
            modeloV.addColumn("Placa");
            modeloV.addColumn("Marca");
            modeloV.addColumn("Modelo");
            modeloV.addColumn("Estilo");
            modeloV.addColumn("Cilindraje");
            modeloV.addColumn("Combustible");
            modeloV.addColumn("Transmision");
            modeloV.addColumn("Pasajeros");
            modeloV.addColumn("Color");

            //
            Object[] lineasTablaV = buffer.lines().toArray();

            //
            for (int i = 0; i < lineasTablaV.length; i++) {
                String linea = lineasTablaV[i].toString().trim();
                String[] datoFila = linea.split(";");
                //
                modeloV.addRow(datoFila);

            }

        } catch (Exception ex) {
            Logger.getLogger(ventanaListaVehiculosVenta.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//Fin metodo

    //Metodo Mostrar Tabla Compra
    public void mostrarTablaCompra() {

        File archivo = new File(rutaArchivoVehiculosC);

        //Try Catch
        try {
            BufferedReader buffer = new BufferedReader(new FileReader(archivo));
            DefaultTableModel modeloC = (DefaultTableModel) tblTablaCompra.getModel();

            modeloC.addColumn("Cedula");
            modeloC.addColumn("Placa");
            modeloC.addColumn("Marca");
            modeloC.addColumn("Modelo");
            modeloC.addColumn("Estilo");
            modeloC.addColumn("Cilindraje");
            modeloC.addColumn("Combustible");
            modeloC.addColumn("Transmision");
            modeloC.addColumn("Pasajeros");
            modeloC.addColumn("Color");

            //
            Object[] lineasTablaC = buffer.lines().toArray();

            //
            for (int i = 0; i < lineasTablaC.length; i++) {
                String linea = lineasTablaC[i].toString().trim();
                String[] datoFila = linea.split(";");
                //
                modeloC.addRow(datoFila);

            }

        } catch (Exception ex) {
            Logger.getLogger(ventanaListaVehiculosVenta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//Fin Mostrar Tabla Compra

    public void filtro() {
        filtro = txtBusquedaVehiculo.getText();
        trsFiltro.setRowFilter(RowFilter.regexFilter(txtBusquedaVehiculo.getText(), 0));
    }
    
    //Metodo para guardar los datos y pasarlos a otro archivo
    public void guardarCompra() throws IOException{
         //Código para validar la compra y hacer el movimiento de archivos
         
         //variables y definicion de las rutas de los archivos
        String ced = "";
        Scanner ScnEntrada = new Scanner(System.in);
        
        File archivoVenta = new File(rutaArchivoVehiculosV);
        
        File archivoCompra = new File(rutaArchivoVehiculosC);
        
        String rutaArchivoTemp = "F:\\Progra 1\\Proyecto 2\\proyectoAgenciaVehiculos\\ Archivo temporal venta/compra.txt";
        File archivoTemp = new File(rutaArchivoTemp);
        
        
         //arraysList
        ArrayList<String> Lista1 = new ArrayList();
        
         //lectura del primer archivo
        BufferedReader br = null;
        try {
            br = new BufferedReader(new FileReader(archivoVenta));
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ventanaCompraVehiculo.class.getName()).log(Level.SEVERE, null, ex);
        }
        //puntear linea y br en memoria
        String linea = br.readLine();
        
        while (linea != null) {
            //agrega lineas y lee siguiente
            Lista1.add(linea);
            linea = br.readLine();
        }//fin while
        
        br.close();
        //TODOS LOS QUE SEAN PRINT INTENTAR CAMBIARLOS A DIALOG MESSAGE O A UNA VENTANA EMERGENTE!!!
         System.out.println("Lista en arreglo:");
        System.out.println("");
        
        for (String i : Lista1) {
            System.out.println(i);
        }//for arreglo

        System.out.println("");
        System.out.println("Digite una ced");
        System.out.println("");
        //AL IGUAL QUE LOS PRINT INTENTAR CAMBIAR EL INGRESO DE DATOS TAL VEZ CON LOS TEXTFIELDS
        ced = ScnEntrada.nextLine();
        
        
        //recorrido para uso del contains
        for (String i : Lista1) {

            if (i.contains(ced)) {

                System.out.println("");
                System.out.println("Ced si esta en el archivo " + i);
                System.out.println("");
                //crea buffered writer (espacio en un buffer)
                BufferedWriter bw = new BufferedWriter(new FileWriter(archivoCompra));
                //escribe la seleccion
                bw.write(i);
                bw.close();

                //borrar dato del input
                if (i.contains(ced)) {

                    Lista1.remove(i);
                    break;

                }//if borrar indice

            }//if confirmacion de coincidencia

        }// FIN for
        
         for (String i : Lista1) {

            System.out.println(i);

        }//for

        //puntero archivo 
        BufferedWriter bwTemp = new BufferedWriter(new FileWriter(archivoTemp));

        for (String i : Lista1) {
            bwTemp.write(i);
            bwTemp.newLine();
        }//for escribir archivo temporal

        bwTemp.close();
    }//Fin metodo guardar compra


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnGuardarCompra;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFondoCompra;
    private javax.swing.JLabel lblIndicacionBusqueda;
    private javax.swing.JLabel lblIndicacionCedula;
    private javax.swing.JLabel lblSubtituloCompra;
    private javax.swing.JLabel lblSubtituloVenta;
    private javax.swing.JLabel lblTituloCompra;
    private javax.swing.JTable tblListaVehiculosVenta;
    private javax.swing.JTable tblTablaCompra;
    private javax.swing.JScrollPane tblTablaVerVenta;
    private javax.swing.JTextField txtBusquedaVehiculo;
    private javax.swing.JTextField txtCedulaCompra;
    // End of variables declaration//GEN-END:variables
}
