/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package proyectoagenciavehiculos;

import javax.swing.JOptionPane;

/**
 *
 * @author 3st3b
 */
public class ventanaVentaVehiculo extends javax.swing.JDialog {
     
//Instanciar los objetos para trabajar con otras clases y archivos
    ventaVehiculo iVehiculosVenta = new ventaVehiculo();
    archivoVentaVehiculos iArchivoVehiculosVenta = new archivoVentaVehiculos();

    /**
     * Creates new form ventanaVentaVehiculo
     */
    public ventanaVentaVehiculo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTituloVenta = new javax.swing.JLabel();
        lblPlaca = new javax.swing.JLabel();
        lblMarca = new javax.swing.JLabel();
        lblModelo = new javax.swing.JLabel();
        lblEstilo = new javax.swing.JLabel();
        lblCilindraje = new javax.swing.JLabel();
        lblCombustible = new javax.swing.JLabel();
        lblTransmision = new javax.swing.JLabel();
        lblCantidadPasajeros = new javax.swing.JLabel();
        lblColor = new javax.swing.JLabel();
        lblCedula = new javax.swing.JLabel();
        txtPlaca = new javax.swing.JTextField();
        txtMarca = new javax.swing.JTextField();
        txtModelo = new javax.swing.JTextField();
        txtEstilo = new javax.swing.JTextField();
        txtCilindraje = new javax.swing.JTextField();
        txtCombustible = new javax.swing.JTextField();
        txtTransmision = new javax.swing.JTextField();
        txtPasajeros = new javax.swing.JTextField();
        txtColor = new javax.swing.JTextField();
        txtCedula = new javax.swing.JTextField();
        btnGuardarVenta = new javax.swing.JButton();
        lblFondoVenta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloVenta.setFont(new java.awt.Font("Dialog", 3, 30)); // NOI18N
        lblTituloVenta.setForeground(new java.awt.Color(204, 204, 204));
        lblTituloVenta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloVenta.setText("Vender Un Vehículo");
        getContentPane().add(lblTituloVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 310, 40));

        lblPlaca.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblPlaca.setForeground(new java.awt.Color(204, 204, 204));
        lblPlaca.setText("Placa:");
        getContentPane().add(lblPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 70, -1));

        lblMarca.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblMarca.setForeground(new java.awt.Color(204, 204, 204));
        lblMarca.setText("Marca:");
        getContentPane().add(lblMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, 20));

        lblModelo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblModelo.setForeground(new java.awt.Color(204, 204, 204));
        lblModelo.setText("Modelo:");
        getContentPane().add(lblModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        lblEstilo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblEstilo.setForeground(new java.awt.Color(204, 204, 204));
        lblEstilo.setText("Estilo:");
        getContentPane().add(lblEstilo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        lblCilindraje.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblCilindraje.setForeground(new java.awt.Color(204, 204, 204));
        lblCilindraje.setText("Cilindraje:");
        getContentPane().add(lblCilindraje, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        lblCombustible.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblCombustible.setForeground(new java.awt.Color(204, 204, 204));
        lblCombustible.setText("Combustible:");
        getContentPane().add(lblCombustible, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 110, -1));

        lblTransmision.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblTransmision.setForeground(new java.awt.Color(204, 204, 204));
        lblTransmision.setText("Transmision:");
        getContentPane().add(lblTransmision, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));

        lblCantidadPasajeros.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblCantidadPasajeros.setForeground(new java.awt.Color(204, 204, 204));
        lblCantidadPasajeros.setText("Cantidad de pasajeros:");
        getContentPane().add(lblCantidadPasajeros, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, -1));

        lblColor.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblColor.setForeground(new java.awt.Color(204, 204, 204));
        lblColor.setText("Color:");
        getContentPane().add(lblColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, -1, -1));

        lblCedula.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblCedula.setForeground(new java.awt.Color(204, 204, 204));
        lblCedula.setText("Cédula:");
        getContentPane().add(lblCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));
        getContentPane().add(txtPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 210, -1));

        txtMarca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMarcaKeyTyped(evt);
            }
        });
        getContentPane().add(txtMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 210, -1));
        getContentPane().add(txtModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 210, -1));
        getContentPane().add(txtEstilo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 210, -1));

        txtCilindraje.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCilindrajeKeyTyped(evt);
            }
        });
        getContentPane().add(txtCilindraje, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 210, -1));

        txtCombustible.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCombustibleKeyTyped(evt);
            }
        });
        getContentPane().add(txtCombustible, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 210, -1));

        txtTransmision.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTransmisionKeyTyped(evt);
            }
        });
        getContentPane().add(txtTransmision, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 210, -1));

        txtPasajeros.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPasajerosKeyTyped(evt);
            }
        });
        getContentPane().add(txtPasajeros, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 210, -1));

        txtColor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtColorKeyTyped(evt);
            }
        });
        getContentPane().add(txtColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 210, -1));

        txtCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCedulaKeyTyped(evt);
            }
        });
        getContentPane().add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 210, -1));

        btnGuardarVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/agregar.png"))); // NOI18N
        btnGuardarVenta.setText("Guardar Datos");
        btnGuardarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarVentaActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardarVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, 160, 50));

        lblFondoVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Fondo Venta Vehiculo.jpg"))); // NOI18N
        getContentPane().add(lblFondoVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarVentaActionPerformed
        // TODO add your handling code here:
         //Guardar Cedula del vendedor
        iVehiculosVenta.setCedulaV(txtCedula.getText());
         //Guardar Placa del vendedor
        iVehiculosVenta.setPlacaV(txtPlaca.getText()); 
        //Guardar Marca del vendedor
        iVehiculosVenta.setMarcaV(txtMarca.getText());
        //Guardar Modelo del vendedor
        iVehiculosVenta.setModeloV(txtModelo.getText());
        //Guardar Estilo de auto del vendedor
        iVehiculosVenta.setEstiloV(txtEstilo.getText());
        //Guardar el cilindraje del vendedor
        iVehiculosVenta.setCilindrajeV(txtCilindraje.getText());
        //Guardar Tipo de combustible del vendedor
        iVehiculosVenta.setCombustibleV(txtCombustible.getText());
        //Guardar transmision del vendedor
        iVehiculosVenta.setTransmisionV(txtTransmision.getText());
        //Guardar cantidad de pasajeros del auto del vendedor
        iVehiculosVenta.setPasajerosV(txtPasajeros.getText());
        //Guardar Color del auto del vendedor
        iVehiculosVenta.setColorV(txtColor.getText());
        
        
        //Escribir en el archivo txt
        iArchivoVehiculosVenta.EscribirVehiculoV(iVehiculosVenta);
        
        //Mostrar el mensaje de guardado
        JOptionPane.showMessageDialog(null, "¡Los datos del vehiculo para su venta se han guardado con exito!", null, JOptionPane.INFORMATION_MESSAGE);
        
        //Poner los textFields en blanco
        txtCedula.setText("");
        txtPlaca.setText("");
        txtMarca.setText("");
        txtModelo.setText("");
        txtEstilo.setText("");
        txtCilindraje.setText("");
        txtCombustible.setText("");
        txtTransmision.setText("");
        txtPasajeros.setText("");
        txtColor.setText("");
    }//GEN-LAST:event_btnGuardarVentaActionPerformed
    //Validaciones
    private void txtCedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCedulaKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(Character.isLetter(c)){
            evt.consume();
            JOptionPane.showMessageDialog(this, "Por favor escriba solo numeros en este campo", "AVISO",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_txtCedulaKeyTyped

    private void txtMarcaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMarcaKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(Character.isDigit(c)){
            evt.consume();
            JOptionPane.showMessageDialog(this, "Por favor escriba solo letras en este campo", "AVISO",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_txtMarcaKeyTyped

    private void txtCilindrajeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCilindrajeKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(Character.isLetter(c)){
            evt.consume();
            JOptionPane.showMessageDialog(this, "Por favor escriba solo numeros en este campo", "AVISO",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_txtCilindrajeKeyTyped

    private void txtCombustibleKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCombustibleKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(Character.isDigit(c)){
            evt.consume();
            JOptionPane.showMessageDialog(this, "Por favor escriba solo letras en este campo", "AVISO",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_txtCombustibleKeyTyped

    private void txtTransmisionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTransmisionKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(Character.isDigit(c)){
            evt.consume();
            JOptionPane.showMessageDialog(this, "Por favor escriba solo letras en este campo", "AVISO",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_txtTransmisionKeyTyped

    private void txtPasajerosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasajerosKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(Character.isLetter(c)){
            evt.consume();
            JOptionPane.showMessageDialog(this, "Por favor escriba solo numeros en este campo", "AVISO",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_txtPasajerosKeyTyped

    private void txtColorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtColorKeyTyped
        // TODO add your handling code here:
         char c = evt.getKeyChar();
        if(Character.isDigit(c)){
            evt.consume();
            JOptionPane.showMessageDialog(this, "Por favor escriba solo letras en este campo", "AVISO",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_txtColorKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaVentaVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaVentaVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaVentaVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaVentaVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ventanaVentaVehiculo dialog = new ventanaVentaVehiculo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarVenta;
    private javax.swing.JLabel lblCantidadPasajeros;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JLabel lblCilindraje;
    private javax.swing.JLabel lblColor;
    private javax.swing.JLabel lblCombustible;
    private javax.swing.JLabel lblEstilo;
    private javax.swing.JLabel lblFondoVenta;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JLabel lblPlaca;
    private javax.swing.JLabel lblTituloVenta;
    private javax.swing.JLabel lblTransmision;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCilindraje;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtCombustible;
    private javax.swing.JTextField txtEstilo;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtPasajeros;
    private javax.swing.JTextField txtPlaca;
    private javax.swing.JTextField txtTransmision;
    // End of variables declaration//GEN-END:variables
}
